#!/usr/bin/env bash
# Generated by interflow plan apply — bootstrap a server for interflow nodes.
# Machine-scope only: user, dirs, optional bin/ — no units are installed
# here and no service is touched; re-running never duplicates the user.
# Run as root from the dist root: sudo bash install.sh
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "install.sh must run as root (sudo bash install.sh)" >&2
  exit 1
fi

INTERFLOW_USER=interflow
INTERFLOW_GROUP=interflow
SRV_ROOT=/srv/interflow

if ! getent group "$INTERFLOW_GROUP" >/dev/null; then
  groupadd --system "$INTERFLOW_GROUP"
fi
if ! id "$INTERFLOW_USER" >/dev/null 2>&1; then
  useradd --system --gid "$INTERFLOW_GROUP" --home-dir "$SRV_ROOT" \
    --shell /usr/sbin/nologin "$INTERFLOW_USER"
  echo "created system user $INTERFLOW_USER"
fi

install -d -o "$INTERFLOW_USER" -g "$INTERFLOW_GROUP" -m 0750 \
  "$SRV_ROOT" "$SRV_ROOT/packs"

# Registrar data layout (content is operator-copied; see
# systemd/interflow-registrar.service for the bootstrap commands).
install -d -o "$INTERFLOW_USER" -g "$INTERFLOW_GROUP" -m 0750 \
  "$SRV_ROOT/registrar" "$SRV_ROOT/registrar/issuer" \
  "$SRV_ROOT/registrar/tls"

# Optional: ship binaries in bin/ next to this script and they get installed.
if [[ -d bin ]]; then
  install -m 0755 bin/* /usr/local/bin/
fi

# Units are not installed here. Node units are written and enabled by
# `interflow node install --pack packs/<kind>-<node>` — the pack is the
# node's only entry point: a machine gets a unit exactly when that
# node's pack lands on it.

# The registrar unit is not installed here either: follow the
# bootstrap sequence in systemd/interflow-registrar.service.
echo "machine prepared — per node: interflow node install --pack packs/<kind>-<node>"
