// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	loadProfile: () => typedError<Profile, string>(__TAURI_INVOKE("load_profile")),
	saveProfile: (profile: Profile) => typedError<null, string>(__TAURI_INVOKE("save_profile", { profile })),
	generateAgentId: () => __TAURI_INVOKE<string>("generate_agent_id"),
	startTunnel: (config: TunnelConfig) => typedError<null, string>(__TAURI_INVOKE("start_tunnel", { config })),
	stopTunnel: () => typedError<null, string>(__TAURI_INVOKE("stop_tunnel")),
	getState: () => typedError<TunnelState, string>(__TAURI_INVOKE("get_state")),
	getRecentLogs: () => typedError<LogLine[], string>(__TAURI_INVOKE("get_recent_logs")),
	/**
	 *  Clears the backend ring buffer too, not just the frontend view — the
	 *  buffer is replayed on webview reload/reconnect, so a view-only clear
	 *  would resurrect the cleared lines.
	 */
	clearLogs: () => typedError<null, string>(__TAURI_INVOKE("clear_logs")),
};

/** Events */
export const events = {
	log: makeEvent<LogEvent>("log"),
	tunnelState: makeEvent<TunnelStateEvent>("tunnel-state"),
};

/* Types */
/**  `log` event payload (tracing capture pump → frontend log panel). */
export type LogEvent = LogLine;

/**  A single log line pushed to the frontend. */
export type LogLine = {
	ts: string,
	level: string,
	target: string,
	message: string,
};

/**  Persisted expose profile (mirrors expose `profile::Profile`). */
export type Profile = {
	/**  Hub URL (e.g. `https://hub.example.com:6666`). */
	hub_url?: string | null,
	/**  Client certificate PEM path (mTLS identity; CN must equal agent_id). */
	client_cert?: string | null,
	/**  Client key PEM path (0600). */
	client_key?: string | null,
	/**
	 *  agent_id used by this machine's expose (edge routes.toml must
	 *  reference the same id).
	 */
	agent_id?: string | null,
	/**
	 *  Path to the trusted hub CA certificate PEM (required when the hub uses
	 *  a self-signed cert).
	 */
	ca_path?: string | null,
	/**  Local ports used last time (for GUI form prefill). */
	local_ports?: number[] | null,
	/**  Transport toward the hub: `h2` (default) or `quic`. */
	transport?: Transport | null,
	/**
	 *  Hub QUIC address (`host:port`); `None` derives it at runtime from
	 *  `hub_url`'s host:port.
	 */
	hub_quic_addr?: string | null,
};

/**  Transport toward the hub (wire form mirrors mesh `TransportKind`). */
export type Transport = "h2" | "quic";

/**  Parameters for starting the tunnel (frontend form → Rust). */
export type TunnelConfig = {
	local_ports: number[],
	hub_url: string,
	client_cert: string,
	client_key: string,
	agent_id: string,
	ca_path: string | null,
	/**  Transport toward the hub; absent = h2 (the default). */
	transport: Transport | null,
	/**  Hub QUIC address; absent = derived from the hub URL's host:port. */
	hub_quic_addr: string | null,
};

/**
 *  Tunnel lifecycle state (wire form mirrors mesh `AgentState`, externally
 *  tagged: `"Connecting" | { "Connected": … } | …`). `backoff_secs` narrows
 *  u64 → u32: specta forbids BigInt-style exports, and a reconnect backoff
 *  beyond u32::MAX seconds is meaningless.
 */
export type TunnelState = "Connecting" | ({ Connected: {
	agent_id: string,
} }) & { Failed?: never; Reconnecting?: never } | ({ Reconnecting: {
	reason: string,
	backoff_secs: number,
} }) & { Connected?: never; Failed?: never } | "Stopped" | ({ Failed: {
	error: string,
} }) & { Connected?: never; Reconnecting?: never };

/**  `tunnel-state` event payload (emitted from the TunnelManager state sink). */
export type TunnelStateEvent = TunnelState;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

